// ReactApp/src/pages/Profile.jsx
import React, { useState, useEffect } from 'react';
import Swal from 'sweetalert2';
import 'sweetalert2/dist/sweetalert2.min.css';
import { Button } from '@mui/material';
import TextField from '@mui/material/TextField';
import EditIcon from '@mui/icons-material/Edit';
import SaveIcon from '@mui/icons-material/Save';
import DoDisturbIcon from '@mui/icons-material/DoDisturb';
import PasswordIcon from '@mui/icons-material/Password';
import axios from 'axios';
import { Header, UpdatePassword } from '../components';
import { useStateContext } from '../contexts/ContextProvider';
import config from '../config.json';

const Profile = () => {
  const { activeMenu, setUser, user, screenSize } = useStateContext();
  const [edit, setEdit] = useState(false);
  const [changePassword, setChangePassword] = useState(false);

  useEffect(async () => {
    Swal.fire({
      title: 'A Carregar...',
      allowOutsideClick: false,
      allowEscapeKey: false,
      showConfirmButton: false,
      background: user.appMode === 'dark' ? '#a1a6ad' : '#FFFFFF',
      iconColor: user.appColor,
    });

    Swal.close();
  }, []);

  const handleSave = async () => {
    if (user.name !== '' && user.email !== '' && user.appColor !== '' && user.appMode !== '') {
      Swal.fire({
        title: 'Tem a Certeza?',
        text: 'Os dados deste Utilizador vão ser atualizados!',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Sim',
        cancelButtonText: 'Cancelar',
        iconColor: user.appColor,
        background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
      }).then(async (result) => {
        if (result.isConfirmed) {
          try {
            const res = await axios.put(`${config.server.apiurl}/user/update`, { userId: user._id, user });
            if (res.data === 'NOK') {
              Swal.fire({
                title: 'Erro!',
                text: 'Não foi possível atualizar os dados deste utilizador!',
                icon: 'error',
                timer: 1500,
                showConfirmButton: false,
                timerProgressBar: true,
                allowOutsideClick: false,
                iconColor: user.appColor,
                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
              }).then(() => {
                setEdit(false);
              });
            } else if (res.data === null) {
              Swal.fire({
                title: 'Erro!',
                text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
                icon: 'error',
                timer: 1500,
                showConfirmButton: false,
                timerProgressBar: true,
                allowOutsideClick: false,
                iconColor: user.appColor,
                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
              });
            } else {
              Swal.fire({
                title: 'Sucesso!',
                text: 'Os dados deste utilizador foram atualizados!',
                icon: 'success',
                timer: 1500,
                showConfirmButton: false,
                timerProgressBar: true,
                allowOutsideClick: false,
                iconColor: user.appColor,
                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
              }).then(() => {
                setUser(user);
                setEdit(false);
              });
            }
          } catch (error) {
            console.error(error);
            Swal.fire({
              title: 'Erro!',
              text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
              icon: 'error',
              timer: 1500,
              showConfirmButton: false,
              timerProgressBar: true,
              allowOutsideClick: false,
              iconColor: user.appColor,
              background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
            });
          }
        }
      });
    }
  };

  const closeChangePassword = async () => {
    setChangePassword(false);
  };

  const handleCancel = () => {
    Swal.fire({
      title: 'Tem a Certeza?',
      text: 'Todas as alterações serão descartadas!',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sim',
      cancelButtonText: 'Cancelar',
      iconColor: user.appColor,
      background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
    }).then(async (result) => {
      if (result.isConfirmed) {
        const res = await axios.get(`${config.server.apiurl}/user/${user._id}`);
        setUser(res.data);
        setEdit(false);
      }
    });
  };

  return (
    <>
      <div className={`fixed component z-10 mr-1 top-12 right-0 ${activeMenu && screenSize > 900 ? 'w-[calc(100%-295px)] ' : 'w-[calc(100%-7px)]'} p-2 shadow-md shadow-black dark:bg-gray-400 bg-white rounded-md`}>
        <div className="flex">
          <Header category="Page" title="Perfil" />
        </div>
        {!edit ? (
          <>
            <Button
              style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
              onClick={() => setEdit(true)}
            >
              <EditIcon />Editar
            </Button>

            <Button
              style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
              onClick={() => setChangePassword(true)}
            >
              <PasswordIcon />Alterar Palavra-Passe
            </Button>
          </>
        ) : (
          <>
            <Button
              style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
              onClick={() => handleSave()}
            >
              <SaveIcon />Guardar
            </Button>
            <Button
              style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
              onClick={() => handleCancel()}
            >
              <DoDisturbIcon />Cancelar
            </Button>
          </>
        )}
      </div>

      <div className={`fixed component mt-[180px] mr-2 p-3 bottom-2 -top-4 right-0 ${activeMenu && screenSize > 900 ? 'w-[calc(100%-305px)]' : 'w-[calc(100%-15px)]'} dark:bg-gray-400 bg-white rounded-md overflow-y-scroll`}>
      {changePassword && <UpdatePassword open={changePassword} setAdd={closeChangePassword} />}
        {edit ? (
          <>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <TextField
                  error={user.username === ''}
                  helperText={user.username === '' ? 'Obrigatório' : ''}
                  autoFocus
                  margin="dense"
                  label="Nome de Utilizador"
                  type="text"
                  fullWidth
                  disabled
                  value={user.username}
                  variant="standard"
                />
              </div>
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <TextField
                  error={user.name === ''}
                  helperText={user.name === '' ? 'Obrigatório' : ''}
                  margin="dense"
                  label="Nome"
                  type="text"
                  fullWidth
                  disabled={!edit}
                  value={user.name}
                  onChange={(e) => setUser({
                    ...user,
                    name: e.target.value,
                  })}
                  variant="standard"
                />
              </div>
            </div>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <TextField
                  error={user.email === ''}
                  helperText={user.email === '' ? 'Obrigatório' : ''}
                  margin="dense"
                  label="Email"
                  type="text"
                  fullWidth
                  disabled={!edit}
                  value={user.email}
                  onChange={(e) => setUser({
                    ...user,
                    email: e.target.value,
                  })}
                  variant="standard"
                />
              </div>
              <div className="w-full md:w-1/2 px-3">
                <label className="text-xl mr-2">Tipo:</label>
                <label className="text-xl font-extrabold break-words">
                  {user.tipo === 'admin' ? 'Administrador' : 'Utilizador'}
                </label>
              </div>

            </div>
          </>
        ) : (
          <>
            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label className="text-xl mr-2">Nome de Utilizador:</label>
                <label className="text-xl font-extrabold break-words">{user.username}</label>
              </div>

              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label className="text-xl mr-2">Nome:</label>
                <label className="text-xl font-extrabold break-words">{user.name}</label>
              </div>
            </div>

            <div className="flex flex-wrap -mx-3 mb-6">
              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label className="text-xl mr-2 break-keep">E-mail:</label>
                <label className="text-xl font-extrabold break-words">{user.email}</label>
              </div>

              <div className="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label className="text-xl mr-2">Tipo:</label>
                <label className="text-xl font-extrabold break-words">
                  {user.tipo === 'admin' ? 'Administrador' : 'Utilizador'}
                </label>
              </div>

            </div>
          </>
        )}

      </div>
    </>
  );
};

export default Profile;

// AngularApp/src/app/pages/profile/profile.component.ts
import { Component } from '@angular/core';
import { animate, state, style, transition, trigger } from '@angular/animations';
import { User } from 'src/app/interfaces/user.interface';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { ConfigService } from 'src/services/configfile/config.service';
import { AuthGuard } from 'src/services/auth/auth-guard.service';
import { MatDialog } from '@angular/material/dialog';
import { ChangePasswordComponent } from 'src/app/components/change-password/change-password.component';
import axios from 'axios';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss'],
  animations: [
    trigger('fade', [
      transition(':enter', [
        style({ opacity: 0 }),
        animate("200ms", style({ opacity: 1 }))
      ])
    ])
  ]
})
export class ProfileComponent {
  apiUrl: string = '';
  isScreenSizeLessThan1200 = false;
  edit: boolean = false;
  userId: String = '';
  username: String = '';
  color: string = '';
  appMode: string = '';
  user: User = {
    _id: '',
    username: '',
    name: '',
    tipo: '',
    appColor: '',
    appMode: '',
    email: '',
    estado: 1
  }

  constructor(public dialog: MatDialog, private authGuard: AuthGuard, private breakpointObserver: BreakpointObserver, private configService: ConfigService) {
    this.userId = this.authGuard.getId();
    this.username = this.authGuard.getUserName();
    this.color = this.authGuard.getAppColor();
    this.appMode = this.authGuard.getAppMode();
  }

  async ngOnInit() {
    Swal.fire({
      title: 'A Carregar...',
      allowOutsideClick: false,
      allowEscapeKey: false,
      showConfirmButton: false,
      iconColor: this.color,
      background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
    });
    this.breakpointObserver.observe([Breakpoints.XSmall, Breakpoints.Small]).subscribe(result => {
      this.isScreenSizeLessThan1200 = result.matches;
    });
    await this.loadApiUrl();

    const res = await axios.get<User>(`${this.apiUrl}/user/${this.userId}`);
    if (res.data === null) {
      Swal.fire({
        title: 'Erro!',
        text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
        icon: 'error',
        timer: 1500,
        showConfirmButton: false,
        timerProgressBar: true,
        allowOutsideClick: false,
        iconColor: this.color,
        background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
      })
    } else {
      this.user = res.data;
    }

    Swal.close();
  }

  updateUser() {
    if (this.user.name !== '' && this.user.email !== '' && this.user.appColor !== '' && this.user.appMode !== '') {
      Swal.fire({
        title: 'Tem a Certeza?',
        text: 'Os dados deste Utilizador vão ser atualizados!',
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Sim',
        cancelButtonText: 'Cancelar',
        iconColor: this.color,
        background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
      }).then(async (result) => {
        if (result.isConfirmed) {
          await this.loadApiUrl();
          const tempUser: User = this.user;
          const res = await axios.put(`${this.apiUrl}/user/update`, { userId: this.userId, user: this.user });
          if (res.data === 'NOK') {
            Swal.fire({
              title: 'Erro!',
              text: 'Não foi possível atualizar os dados deste utilizador!',
              icon: 'error',
              timer: 1500,
              showConfirmButton: false,
              timerProgressBar: true,
              allowOutsideClick: false,
              iconColor: this.color,
              background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
            }).then(() => {
              this.user = tempUser;
              this.edit = false;
            });
          } else if (res.data === null) {
            Swal.fire({
              title: 'Erro!',
              text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
              icon: 'error',
              timer: 1500,
              showConfirmButton: false,
              timerProgressBar: true,
              allowOutsideClick: false,
              iconColor: this.color,
              background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
            })
          } else {
            Swal.fire({
              title: 'Sucesso!',
              text: 'Os dados deste utilizador from atualizados!',
              icon: 'success',
              timer: 1500,
              showConfirmButton: false,
              timerProgressBar: true,
              allowOutsideClick: false,
              iconColor: this.color,
              background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
            }).then(() => {

              if (this.username === this.user.username) {
                this.authGuard.updateUser(tempUser);
              }
              window.location.reload();
            });
          }
        }
      });
    }
  }

  resetPassword() {
    Swal.fire({
      title: 'Tem a Certeza?',
      text: 'A palavra-passe vair ser restaurada!',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sim',
      cancelButtonText: 'Cancelar',
      iconColor: this.color,
      background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
    }).then(async (result) => {
      if (result.isConfirmed) {
        await this.loadApiUrl();
        const tempUser: User = this.user;
        const res = await axios.put(`${this.apiUrl}/user/resetpassword`, { userId: this.userId, user: this.user });
        if (res.data === null) {
          Swal.fire({
            title: 'Erro!',
            text: 'Não foi possível restaurar a palavra-passe!',
            icon: 'error',
            timer: 1500,
            showConfirmButton: false,
            timerProgressBar: true,
            allowOutsideClick: false,
            iconColor: this.color,
            background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
          });
        } else {
          Swal.fire({
            title: 'Sucesso!',
            text: 'A palavra-passe foi restaurada!',
            icon: 'success',
            timer: 1500,
            showConfirmButton: false,
            timerProgressBar: true,
            allowOutsideClick: false,
            iconColor: this.color,
            background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
          });
        }
      }
    });
  }

  cancelEdit() {
    Swal.fire({
      title: 'Tem a Certeza?',
      text: 'Todas as alterações serão descartadas!',
      icon: 'warning',
      showCancelButton: true,
      confirmButtonColor: '#3085d6',
      cancelButtonColor: '#d33',
      confirmButtonText: 'Sim',
      cancelButtonText: 'Cancelar',
      iconColor: this.color,
      background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
    }).then(async (result) => {
      if (result.isConfirmed) {
        window.location.reload();
      }
    });
  }

  private async loadApiUrl() {
    return new Promise<void>((resolve) => {
      this.configService.getApiBaseUrl().subscribe(apiUrl => {
        this.apiUrl = apiUrl;
        resolve();
      });
    });
  }

  openPopup(): void {
    this.dialog.open(ChangePasswordComponent, {
      width: '400px',
      data: {
        title: 'Popup Title',
        content: 'This is the content of the popup.'
      }
    });
  }
}

<div @fade class="w-full h-fit z-50 shadow-xl shadow-slate-500 sticky rounded-lg p-2"
    [style.background]="appMode==='dark' ? '#b0b5b5':'white'">
    <app-header [title]="'Perfil'" [back]="''" [hasfilters]="true"></app-header>
    <div *ngIf="!edit">
        <button (click)="edit=true" class=" ml-2 mr-2 text-white p-2 rounded-md" [style.background-color]="color">
            <i class="fa fa-pencil p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Editar</i>
        </button>
        <button *ngIf="user.username === username || user.username !== 'admin'" class="mr-2 text-white p-2 rounded-md" (click)="openPopup()" [style.background-color]="color">
            <i class="underline">****</i> <i *ngIf="!isScreenSizeLessThan1200"> Alterar Palavra-Passe</i>
        </button>
    </div>
    <div *ngIf="edit">
        <button (click)="updateUser()" class="mr-2 text-white p-2 rounded-md" style="color:white"
            [style.background-color]="color">
            <i class="fa fa-floppy-disk p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Guardar</i>
        </button>
        <button (click)="cancelEdit()" class="mr-2 bg-red-600 text-white p-2 rounded-md">
            <i class="fa fa-ban p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Cancelar</i>
        </button>
    </div>
</div>
<div @fade *ngIf="!edit" class="w-full mt-6 grid grid-cols-1 md:grid-cols-2 gap-4 p-4 rounded-lg shadow-xl shadow-slate-500"
    [style.background]="appMode==='dark' ? '#b0b5b5':'white'">
    <div>
        <label class="text-xl mr-2">Nome de Utilizador:</label>
        <label class="text-xl font-extrabold break-words">{{user.username}}</label>
    </div>

    <div>
        <label class="text-xl mr-2">Nome:</label>
        <label class="text-xl font-extrabold break-words">{{user.name}}</label>
    </div>

    <div>
        <label class="text-xl mr-2 break-keep">E-mail:</label>
        <label class="text-xl font-extrabold break-words">{{user.email}}</label>
    </div>

    <div></div>

    <div class="flex">
        <label class="text-xl mr-2">Cor da Aplicação:</label>
        <div class="w-20 h-8 rounded-lg -mt-0.5" [style.background-color]="user.appColor"></div>
    </div>

    <div>
        <label class="text-xl mr-2">Modo da Aplicação:</label>
        <label class="text-xl font-extrabold">{{user.appMode==='dark' ? 'Escuro' : 'Claro'}}</label>
    </div>
</div>

<div @fade *ngIf="edit" class="w-full mt-5 grid grid-cols-1 md:grid-cols-2 gap-4 p-4 rounded-lg shadow"
    [style.background]="appMode==='dark' ? '#b0b5b5':'white'">
    <div class="mt-5">
        <label class="text-xl mr-2">Nome de Utilizador:</label>
        <label class="text-xl font-extrabold break-words">{{user.username}}</label>
    </div>

    <mat-form-field appearance="fill">
        <mat-label>Nome</mat-label>
        <input matInput [(ngModel)]="user.name" required>
        <mat-error>Deve preencher o Nome</mat-error>
    </mat-form-field>

    <mat-form-field appearance="fill">
        <mat-label>E-mail</mat-label>
        <input matInput type="email" [(ngModel)]="user.email" required>
        <mat-error>Deve preencher o E-mail</mat-error>
    </mat-form-field>

    <div></div>


    <mat-form-field appearance="fill">
        <mat-label>Cor da Aplicação</mat-label>
        <input type="color" matInput [(ngModel)]="user.appColor" required>
        <mat-error>Deve preencher a Cor da Aplicação</mat-error>
    </mat-form-field>

    <mat-form-field appearance="fill">
        <mat-label>Modo da Aplicação</mat-label>
        <mat-select [(ngModel)]="user.appMode" required>
            <mat-option value="dark">Escuro</mat-option>
            <mat-option value="light">Claro</mat-option>
        </mat-select>
        <mat-error>Deve preencher o Modo da Aplicação</mat-error>
    </mat-form-field>
</div>
