// AngularApp/src/app/components/licences/licences.component.ts
import { Component, Input } from '@angular/core';
import { AuthGuard } from 'src/services/auth/auth-guard.service';
import { BreakpointObserver, Breakpoints } from '@angular/cdk/layout';
import { animate, style, transition, trigger } from '@angular/animations';
import { ConfigService } from 'src/services/configfile/config.service';
import { Licence } from 'src/app/interfaces/licence.interface';
import axios from 'axios';
import Swal from 'sweetalert2';
import { AddlicencesComponent } from '../addlicences/addlicences.component';
import { MatDialog, MatDialogRef } from '@angular/material/dialog';
import { MatTabChangeEvent } from '@angular/material/tabs';

@Component({
  selector: 'app-licences',
  templateUrl: './licences.component.html',
  styleUrls: ['./licences.component.scss'],
  animations: [
    trigger('fade', [
      transition(':enter', [
        style({ opacity: 0 }),
        animate("200ms", style({ opacity: 1 }))
      ])
    ])
  ]
})
export class LicencesComponent {
  dialogRef: MatDialogRef<AddlicencesComponent> | undefined;
  @Input() clientId: string = '';
  color: string = '';
  appMode: string = '';
  edit: string = '';
  isScreenSizeLessThan1200 = false;
  apiUrl: string = '';
  licences: Licence[] = [];
  userId: string = '';
  selectedLicence: Licence = {
    _id: '',
    clientId: '',
    tipo: '',
    estado: true,
    obs: '',
    startedAt: '',
    endedAt: ''
  };


  constructor(private breakpointObserver: BreakpointObserver, private authGuard: AuthGuard, private configService: ConfigService, public dialog: MatDialog) {
    this.color = this.authGuard.getAppColor();
    this.appMode = this.authGuard.getAppMode();
    this.userId = this.authGuard.getId();
    this.dialogRef = undefined;
  }

  async ngOnInit() {
    this.breakpointObserver.observe([Breakpoints.XSmall, Breakpoints.Small]).subscribe(result => {
      this.isScreenSizeLessThan1200 = result.matches;
    });
    try {
      await this.loadApiUrl();
      const res = await axios.get(`${this.apiUrl}/alllicences/${this.clientId}`);
      this.licences = res.data;
    } catch (error) {
      console.error(error);
      Swal.fire({
        title: 'Erro!',
        text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
        icon: 'error',
        timer: 1500,
        showConfirmButton: false,
        timerProgressBar: true,
        allowOutsideClick: false,
        iconColor: this.color,
        background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
      })
    }
  }

  private async loadApiUrl() {
    return new Promise<void>((resolve) => {
      this.configService.getApiBaseUrl().subscribe(apiUrl => {
        this.apiUrl = apiUrl;
        resolve();
      });
    });
  }

  formatDate(dt: string): string {
    const date = new Date(dt)
    const year = date.getFullYear();
    const month = ("0" + (date.getMonth() + 1)).slice(-2);
    const day = ("0" + date.getDate()).slice(-2);
    return `${year}-${month}-${day}`;
  }

  validateEstado(inicio: string, fim: string, id: string): void {

    const temp: Licence = this.licences.filter((row) => (row._id === id))[0]
    temp.startedAt = inicio
    temp.endedAt = fim
    temp.estado = new Date(temp.startedAt) < new Date(temp.endedAt)
  }

  async saveLicence() {
    try {
      const res = await
        axios.put(`${this.apiUrl}/licence/update`, { userId: this.userId, licence: this.licences.filter((row) => (row._id === this.selectedLicence._id))[0] });
      if (res.data === 'OK') {
        Swal.fire({
          title: 'Sucesso!',
          text: 'A licença foi atualizada com sucesso!',
          icon: 'success',
          timer: 1500,
          showConfirmButton: false,
          timerProgressBar: true,
          allowOutsideClick: false,
          iconColor: this.color,
          background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
        })
        this.edit = '';
      } else {
        Swal.fire({
          title: 'Erro!',
          text: 'Não foi possivel atualiza a licença!',
          icon: 'error',
          timer: 1500,
          showConfirmButton: false,
          timerProgressBar: true,
          allowOutsideClick: false,
          iconColor: this.color,
          background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
        }).then(() => {
          const licenseIndex = this.licences.findIndex((row) => row._id === this.edit);
          this.licences[licenseIndex] = this.selectedLicence;
          this.edit = '';
        })
      }

    } catch (error) {
      console.error(error)
      Swal.fire({
        title: 'Erro!',
        text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
        icon: 'error',
        timer: 1500,
        showConfirmButton: false,
        timerProgressBar: true,
        allowOutsideClick: false,
        iconColor: this.color,
        background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
      })
    }
  }

  cancelEdit() {
    Swal.fire({
      title: 'Aviso!',
      text: 'Todas a alterações serão perdidas. Tem a certeza?',
      icon: 'question',
      showConfirmButton: true,
      showCancelButton: true,
      confirmButtonText: 'Sim',
      cancelButtonText: 'Não',
      allowOutsideClick: false,
      iconColor: this.color,
      background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
    }).then((result) => {
      if (result.isConfirmed) {
        const licenseIndex = this.licences.findIndex((row) => row._id === this.edit);
        this.licences[licenseIndex] = this.selectedLicence;
        this.edit = '';
      }
    })
  }

  deleteLicence() {
    Swal.fire({
      title: 'Aviso!',
      text: 'A licença vai ser apagada. Tem a certeza?',
      icon: 'question',
      showConfirmButton: true,
      showCancelButton: true,
      confirmButtonText: 'Sim',
      cancelButtonText: 'Não',
      allowOutsideClick: false,
      iconColor: this.color,
      background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
    }).then(async (result) => {
      if (result.isConfirmed) {
        try {
          const res = await axios.delete(`${this.apiUrl}/licence/delete/${this.selectedLicence._id}`);

          if (res.data === 'NOK') {
            Swal.fire({
              title: 'Erro!',
              text: 'Não foi possivel apagar a licença!',
              icon: 'error',
              timer: 1500,
              showConfirmButton: false,
              timerProgressBar: true,
              allowOutsideClick: false,
              iconColor: this.color,
              background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
            })
          } else {
            const licenseIndex = this.licences.findIndex((row) => row._id === this.selectedLicence._id);
            this.licences.splice(licenseIndex, 1);
            Swal.fire({
              title: 'Sucesso!',
              text: 'A licença foi apagada!',
              icon: 'success',
              timer: 1500,
              showConfirmButton: false,
              timerProgressBar: true,
              allowOutsideClick: false,
              iconColor: this.color,
              background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
            })
          }

        } catch (error) {
          console.error(error)
          Swal.fire({
            title: 'Erro!',
            text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
            icon: 'error',
            timer: 1500,
            showConfirmButton: false,
            timerProgressBar: true,
            allowOutsideClick: false,
            iconColor: this.color,
            background: this.appMode === 'dark' ? '#b0b5b5' : 'white',
          })
        }
      }
    })

  }

  changeEdit(event: MatTabChangeEvent) {
    const selectedTab = event.tab;
    this.edit = ''
    const { _id, clientId, tipo, estado, obs, startedAt, endedAt } = this.licences.filter((row) => (row._id === selectedTab.ariaLabel))[0];
    this.selectedLicence = { _id, clientId, tipo, estado, obs, startedAt, endedAt };
  }

  openPopup(): void {
    this.dialogRef = this.dialog.open(AddlicencesComponent, {
      width: '400px',
      data: {
        title: 'Popup Title',
        content: this.clientId
      }
    });

    this.dialogRef.afterClosed().subscribe((temp) => {
      if (temp) {
        const newLicence: Licence = {
          _id: temp._id,
          clientId: temp.clientId,
          tipo: temp.tipo,
          estado: temp.estado,
          obs: temp.obs,
          startedAt: temp.startedAt,
          endedAt: temp.endedAt
        };
        this.licences.push(newLicence);
      }

    });
  }
}

<div @fade class="w-full z-50 shadow-xl rounded-lg mt-5 shadow-slate-500  p-2 "
    [style.background]="appMode==='dark' ? '#b0b5b5':'#f2eeed'">
    <p class="mb-2 text-2xl font-semibold">Licenças do Cliente</p>
    <div class="mt-1 mb-5" *ngIf="edit===''">
        <button class=" text-white mr-2 p-2 rounded-md" (click)="openPopup()" [style.background-color]="color">
            <i class="fa fa-plus p-1"></i> <i *ngIf="!isScreenSizeLessThan1200" > Adicionar</i>
        </button>
        <button *ngIf="licences.length>0" (click)="edit=selectedLicence._id"
            class="  mr-2 text-white p-2 rounded-md" [style.background-color]="color">
            <i class="fa fa-pencil p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Editar</i>
        </button>
        <button *ngIf="licences.length>0" class="mr-2 bg-red-600 text-white p-2 rounded-md" (click)="deleteLicence()">
            <i class="fa fa-trash p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Apagar</i>
        </button>
    </div>

    <div class="mt-1 mb-5" *ngIf="edit!==''">
        <button class="mr-2 text-white p-2 rounded-md" style="color:white" [style.background-color]="color" (click)="saveLicence()">
            <i class="fa fa-floppy-disk p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Guardar</i>
        </button>
        <button class="mr-2 bg-red-600 text-white p-2 rounded-md" (click)="cancelEdit()">
            <i class="fa fa-ban p-1"></i> <i *ngIf="!isScreenSizeLessThan1200"> Cancelar</i>
        </button>
    </div>
    <mat-tab-group class="mt-1" (selectedTabChange)="changeEdit($event)" >
        <mat-tab *ngFor="let licence of licences" [label]="licence.tipo.valueOf()" [aria-label]="licence._id" [disabled]="edit!==licence._id && edit!==''">
     
            <div *ngIf="edit===licence._id" class="w-full grid grid-cols-1 gap-4 md:grid-cols-2">
                <div>
                    <mat-form-field class="w-full" appearance="fill">
                        <mat-label>Tipo</mat-label>
                        <input matInput [(ngModel)]="licence.tipo" required>
                        <mat-error>Deve preencher o tipo</mat-error>
                    </mat-form-field>
                </div>

                <div>
                    <label class="text-xl mr-2">Estado:</label>
                    <label class="text-xl font-extrabold break-words">{{licence.estado ? 'Válida' : 'Expirada'}}</label>
                </div>

                <mat-form-field appearance="fill" class="w-full">
                    <mat-label>Data de Inicio</mat-label>
                    <input matInput [matDatepicker]="inicio" [ngModel]="formatDate(licence.startedAt)" (dateInput)="validateEstado($any($event.target).value,licence.endedAt,licence._id)" required>
                    <mat-datepicker-toggle matIconSuffix [for]="inicio"></mat-datepicker-toggle>
                    <mat-datepicker #inicio ></mat-datepicker>
                    <mat-error>Deve preencher o início da licença</mat-error>
                </mat-form-field>

                <mat-form-field appearance="fill" class="w-full">
                    <mat-label>Data de Fim</mat-label>
                    <input matInput [matDatepicker]="fim" [ngModel]="formatDate(licence.endedAt)" (dateInput)="validateEstado(licence.startedAt,$any($event.target).value,licence._id)" required>
                    <mat-datepicker-toggle matIconSuffix [for]="fim"></mat-datepicker-toggle>
                    <mat-datepicker #fim ></mat-datepicker>
                    <mat-error>Deve preencher o fim da licença</mat-error>
                </mat-form-field>

                <div>
                    <mat-form-field class="w-full">
                        <textarea matInput [(ngModel)]="licence.obs" placeholder="Observações"></textarea>
                    </mat-form-field>
                </div>

            </div>
            <div class="mt-2 w-full grid grid-cols-1 md:grid-cols-2" *ngIf="edit!==licence._id">
                <div>
                    <label class="text-xl mr-2">Tipo:</label>
                    <label class="text-xl font-extrabold break-words">{{licence.tipo}}</label>
                </div>
                <div>
                    <label class="text-xl mr-2">Estado:</label>
                    <label class="text-xl font-extrabold break-words">{{licence.estado ? 'Válida' : 'Expirada'}}</label>
                </div>

                <div>
                    <label class="text-xl mr-2">Início da Licença:</label>
                    <label class="text-xl font-extrabold break-words">{{(licence.startedAt).split('T')[0]}}</label>
                </div>
                <div>
                    <label class="text-xl mr-2">Fim da Licença:</label>
                    <label class="text-xl font-extrabold break-words">{{formatDate(licence.endedAt)}}</label>
                </div>

                <div>
                    <label class="text-xl mr-2">Observações:</label>
                    <label class="text-xl font-extrabold break-words">{{licence.obs}}</label>
                </div>
            </div>
        </mat-tab>
    </mat-tab-group>
    <div class="mt-5" *ngIf="!edit">
    
    </div>
</div>

// ReactJS/ReactApp/src/components/Licences.jsx
import React, { useEffect, useState } from 'react'
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Tab from '@mui/material/Tab';
import TabContext from '@mui/lab/TabContext';
import TabList from '@mui/lab/TabList';
import TabPanel from '@mui/lab/TabPanel';
import AddIcon from '@mui/icons-material/Add';
import EditIcon from '@mui/icons-material/Edit';
import DeleteIcon from '@mui/icons-material/Delete';
import SaveIcon from '@mui/icons-material/Save';
import DoDisturbIcon from '@mui/icons-material/DoDisturb';
import { Button } from '@mui/material';
import { useStateContext } from '../contexts/ContextProvider';
import axios from 'axios';
import Swal from 'sweetalert2';
import AddLicence from './AddLicence';

export const Licences = ({ clientId }) => {
    const [value, setValue] = useState('0');
    const [edit, setEdit] = useState('');
    const { user } = useStateContext();
    const [addNew, setAddNew] = useState(false);
    const [licences, setLicences] = useState([{
        clientId: '',
        estado: '',
        tipo: '',
        obs: '',
        startedAt: '',
        endedAt: '',
    }]);

    useEffect(() => {
        const cancelToken = axios.CancelToken.source();
        axios.get(`${process.env.REACT_APP_API_URL}/alllicences/${clientId}`, { cancelToken: cancelToken.token })
            .then((res) => {
                setLicences(res.data);
            }).catch((err) => {
                if (axios.isCancel(err)) {
                    console.log("Operação Cancelada!")
                } else {
                    console.log(err);
                }
            });
        return () => {
            cancelToken.cancel();
        }
    }, [clientId]);

    const handleChange = (event, newValue) => {
        setValue(newValue);
    };

    const handleTipoChange = (newTipo, rowIndex) => {
        const updatedLicences = [...licences];
        updatedLicences[rowIndex].tipo = newTipo;
        setLicences(updatedLicences);
    };

    const handleInicioChange = (newInicio, rowIndex) => {
        const updatedLicences = [...licences];
        if (new Date(updatedLicences[rowIndex].startedAt) > new Date(updatedLicences[rowIndex].endedAt)) {
            updatedLicences[rowIndex].estado = false;
        } else {
            updatedLicences[rowIndex].estado = true;
        }
        updatedLicences[rowIndex].startedAt = newInicio + "T00:00:00.000z";
        setLicences(updatedLicences);
    };

    const handleFimChange = (newFim, rowIndex) => {
        const updatedLicences = [...licences];
        if (new Date(updatedLicences[rowIndex].startedAt) > new Date(updatedLicences[rowIndex].endedAt)) {
            updatedLicences[rowIndex].estado = false;
        } else {
            updatedLicences[rowIndex].estado = true;
        }
        updatedLicences[rowIndex].endedAt = newFim + "T00:00:00.000z";
        setLicences(updatedLicences);
    };

    const handleObsChange = (newObs, rowIndex) => {
        const updatedLicences = [...licences];
        updatedLicences[rowIndex].obs = newObs;
        setLicences(updatedLicences);
    };

    const closeAddModel = async (load) => {
        setAddNew(false);
        if (load) {
            const cancelToken = axios.CancelToken.source();
            axios.get(`${process.env.REACT_APP_API_URL}/alllicences/${clientId}`, { cancelToken: cancelToken.token })
                .then((res) => {
                    setLicences(res.data);
                }).catch((err) => {
                    if (axios.isCancel(err)) {
                        console.log("Operação Cancelada!")
                    } else {
                        console.log(err);
                    }
                });
        }
      };

    const handleCancel = () => {
        Swal.fire({
            title: 'Tem a Certeza?',
            text: 'Todas as alterações serão descartadas!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim',
            cancelButtonText: 'Cancelar',
            iconColor: user.appColor,
            background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
        }).then(() => {
            const cancelToken = axios.CancelToken.source();
            axios.get(`${process.env.REACT_APP_API_URL}/alllicences/${clientId}`, { cancelToken: cancelToken.token })
                .then((res) => {
                    setLicences(res.data);
                }).catch((err) => {
                    if (axios.isCancel(err)) {
                        console.log("Operação Cancelada!")
                    } else {
                        console.log(err);
                    }
                });
            setEdit('');
        });

    };

    const handleEdit = (value) => {
        setEdit(value);
    };

    const handleSave = () => {
        const cancelToken = axios.CancelToken.source();
        const temp = licences.at(edit);
        console.log(temp)
        Swal.fire({
            title: 'Tem a Certeza?',
            text: 'Os dados da licença vão ser atualizados!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sim',
            cancelButtonText: 'Cancelar',
            iconColor: user.appColor,
            background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
        }).then((result) => {
            if (result.isConfirmed) {

                axios.put(`${process.env.REACT_APP_API_URL}/licence/update`, { userId: user._id, licence: temp, cancelToken: cancelToken.token })
                    .then((res) => {
                        if (res.data === 'NOK') {
                            Swal.fire({
                                title: 'Erro!',
                                text: 'Não foi possível atualizar a Licença!',
                                icon: 'error',
                                timer: 1500,
                                showConfirmButton: false,
                                timerProgressBar: true,
                                iconColor: user.appColor,
                                allowOutsideClick: false,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            }).then(async () => {
                                axios.get(`${process.env.REACT_APP_API_URL}/alllicences/${clientId}`, { cancelToken: cancelToken.token })
                                    .then((res) => {
                                        setLicences(res.data);
                                    }).catch((err) => {
                                        if (axios.isCancel(err)) {
                                            console.log("Operação Cancelada!")
                                        } else {
                                            console.log(err);
                                        }
                                    });
                                setEdit('');
                            });
                        } else if (res.data === null) {
                            Swal.fire({
                                title: 'Erro!',
                                text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
                                icon: 'error',
                                timer: 1500,
                                showConfirmButton: false,
                                timerProgressBar: true,
                                allowOutsideClick: false,
                                iconColor: user.appColor,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            });
                        } else {
                            Swal.fire({
                                title: 'Sucesso!',
                                text: 'Os dados da licença foram atualizados!',
                                icon: 'success',
                                timer: 1500,
                                showConfirmButton: false,
                                timerProgressBar: true,
                                allowOutsideClick: false,
                                iconColor: user.appColor,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            }).then(() => {
                                setEdit('');
                            });
                        }
                    }).catch((err) => {
                        if (axios.isCancel(err)) {
                            console.log("Operação Cancelada!")
                        } else {
                            console.log(err);
                            Swal.fire({
                                title: 'Erro!',
                                text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
                                icon: 'error',
                                timer: 1500,
                                showConfirmButton: false,
                                iconColor: user.appColor,
                                timerProgressBar: true,
                                allowOutsideClick: false,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            });
                        }

                    });
            }
        });
    };

    const handleDelete = async () => {
        const cancelToken = axios.CancelToken.source();
        const temp = licences.at(value)._id;

        Swal.fire({
            title: 'Tem a Certeza?',
            text: 'Vai apagar esta Licença!',
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            iconColor: user.appColor,
            confirmButtonText: 'Sim',
            cancelButtonText: 'Cancelar',
            background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
        }).then(async (result) => {
            if (result.isConfirmed) {
                axios.delete(`${process.env.REACT_APP_API_URL}/licence/delete/${temp}`, { cancelToken: cancelToken.token })
                    .then((res) => {
                        if (res.data === 'NOK') {
                            Swal.fire({
                                title: 'Erro!',
                                text: 'Não foi possível apagar a licença!',
                                icon: 'error',
                                timer: 1500,
                                showConfirmButton: false,
                                timerProgressBar: true,
                                iconColor: user.appColor,
                                allowOutsideClick: false,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            });
                        } else if (res.data === null) {
                            Swal.fire({
                                title: 'Erro!',
                                text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
                                icon: 'error',
                                timer: 1500,
                                showConfirmButton: false,
                                timerProgressBar: true,
                                iconColor: user.appColor,
                                allowOutsideClick: false,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            });
                        } else {
                            Swal.fire({
                                title: 'Sucesso!',
                                text: 'O licença foi apagada!',
                                icon: 'success',
                                timer: 1500,
                                showConfirmButton: false,
                                timerProgressBar: true,
                                iconColor: user.appColor,
                                allowOutsideClick: false,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            }).then(() => {
                                axios.get(`${process.env.REACT_APP_API_URL}/alllicences/${clientId}`, { cancelToken: cancelToken.token })
                                    .then((res) => {
                                        setLicences(res.data);
                                    }).catch((err) => {
                                        if (axios.isCancel(err)) {
                                            console.log("Operação Cancelada!")
                                        } else {
                                            console.log(err);
                                        }
                                    });
                                setValue('0')
                            });
                        }
                    }).catch((err) => {
                        if (axios.isCancel(err)) {
                            console.log("Operação Cancelada!")
                        } else {
                            console.log(err);
                            Swal.fire({
                                title: 'Erro!',
                                text: 'Não foi possível realizar a ligação ao servidor. Por favor tenta mais tarde!',
                                icon: 'error',
                                timer: 1500,
                                showConfirmButton: false,
                                iconColor: user.appColor,
                                timerProgressBar: true,
                                allowOutsideClick: false,
                                background: user.appMode === 'dark' ? '#b0b5b5' : 'white',
                            });
                        }
                    })
            }
        });
    };



    return (

        <Box sx={{ width: '100%', typography: 'body1' }}>
            <p className="text-xl font-extrabold break-words mb-5">Licenças do Cliente</p>
            {edit === '' ? (
                <>
                    <Button
                        style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
                        onClick={() => setAddNew(true)}
                    >
                        <AddIcon />Nova
                    </Button>
                    <Button
                        style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
                        onClick={() => handleEdit(value)}
                    >
                        <EditIcon />Editar
                    </Button>
                    <Button
                        style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
                        onClick={() => handleDelete()}
                    >
                        <DeleteIcon />Apagar
                    </Button>
                </>
            ) : (
                <>
                    <Button
                        style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
                        onClick={() => handleSave()}
                    >
                        <SaveIcon />Guardar
                    </Button>
                    <Button
                        style={{ cursor: 'pointer', backgroundColor: user.appColor, borderRadius: '5px', color: 'white', marginLeft: '12px', marginBottom: '7px', padding: '5px' }}
                        onClick={() => handleCancel()}
                    >
                        <DoDisturbIcon />Cancelar
                    </Button>
                </>
            )}
            {addNew && <AddLicence client={clientId} open={addNew} setAdd={closeAddModel} />}
            <TabContext value={value}>
                <Box sx={{ borderBottom: 1, borderColor: 'divider' }}>
                    <TabList onChange={handleChange}>
                        {licences.map((row, index) =>
                            <Tab disabled={edit !== ''} key={index} label={row.tipo} value={index.toString()} />
                        )}
                    </TabList>
                </Box>
                {licences.map((row, index) => (

                    edit !== index.toString() ? (
                        <TabPanel key={index} value={index.toString()}>
                            <div className="flex flex-wrap -mx-3 mb-6">
                                <div className="w-full md:w-2/2 px-3 mb-6 md:mb-0">
                                    <label className="text-xl mr-2">Tipo:</label>
                                    <label className="text-xl font-extrabold break-words">{row.tipo}</label>
                                </div>
                            </div>
                            <div className="flex flex-wrap -mx-3 mb-6">
                                <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                                    <label className="text-xl mr-2">Estado:</label>
                                    <label className="text-xl font-extrabold break-words">{row.estado ? 'Válida' : 'Expirada'}</label>
                                </div>
                                <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                                    <label className="text-xl mr-2 break-keep">Inicio:</label>
                                    <label className="text-xl font-extrabold break-words">{row.startedAt.split('T')[0]}</label>
                                </div>
                                <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                                    <label className="text-xl mr-2 break-keep">Fim:</label>
                                    <label className="text-xl font-extrabold break-words">{row.endedAt.split('T')[0]}</label>
                                </div>
                            </div>
                            <div className="flex flex-wrap -mx-3 mb-6">
                                <div className="w-full md:w-2/2 px-3 mb-6 md:mb-0">
                                    <label className="text-xl mr-2 break-keep">Observações:</label>
                                    <label className="text-xl font-extrabold break-words">{row.obs}</label>
                                </div>
                            </div>
                        </TabPanel>
                    ) : (
                        <div key={row._id}>
                            <div className="flex flex-wrap -mx-3 mb-6">
                                <div className="w-full md:w-2/2 px-3 mb-6 md:mb-0">
                                    <TextField
                                        error={row.tipo === ''}
                                        helperText={row.tipo === '' ? 'Obrigatório' : ''}
                                        margin="dense"
                                        label="Tipo"
                                        type="text"
                                        fullWidth
                                        value={row.tipo}
                                        variant="standard"
                                        onChange={(e) => handleTipoChange(e.target.value, index)}
                                    />
                                </div>
                            </div>
                            <div className="flex flex-wrap -mx-3 mb-6">
                                <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                                    <label className="text-xl mr-2">Estado:</label>
                                    <label className="text-xl font-extrabold break-words">{row.estado ? 'Válida' : 'Expirada'}</label>
                                </div>
                                <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                                    <TextField
                                        error={row.startedAt === ''}
                                        helperText={row.startedAt === '' ? 'Obrigatório' : ''}
                                        margin="dense"
                                        label="Início"
                                        type="date"
                                        fullWidth
                                        value={row.startedAt.split('T')[0]}
                                        variant="standard"
                                        onChange={(e) => handleInicioChange(e.target.value, index)}
                                    />
                                </div>
                                <div className="w-full md:w-1/3 px-3 mb-6 md:mb-0">
                                    <TextField
                                        error={row.endedAt === ''}
                                        helperText={row.endedAt === '' ? 'Obrigatório' : ''}
                                        margin="dense"
                                        label="Fim"
                                        type="date"
                                        fullWidth
                                        value={row.endedAt.split('T')[0]}
                                        variant="standard"
                                        onChange={(e) => handleFimChange(e.target.value, index)}
                                    />
                                </div>

                            </div>
                            <div className="flex flex-wrap -mx-3 mb-6">
                                <div className="w-full md:w-3/3 px-3 mb-6 md:mb-0">
                                    <TextField
                                        error={row.obs === ''}
                                        helperText={row.obs === '' ? 'Obrigatório' : ''}
                                        margin="dense"
                                        label="Observações"
                                        type="text"
                                        multiline
                                        rows={4}
                                        fullWidth
                                        value={row.obs}
                                        variant="standard"
                                        onChange={(e) => handleObsChange(e.target.value, index)}
                                    />
                                </div>
                            </div>
                        </div>
                    )
                ))}
            </TabContext>
        </Box>
    );
};
